---
substitutions:
  reboot_timeout: 1d
  name: 'heatpump'
  friendly_name: 'Heat Pump'
  static_ip: '192.168.20.83'

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2026.2.4
  project:
    name: "tinwer.mahtanarm"
    version: "1.4"

esp32:
  board: esp32-c3-devkitc-02
  framework:
    type: esp-idf

external_components:
  - source: github://muart-group/esphome-components@main
    components: [mitsubishi_itp]

logger:
  baud_rate: 115200

api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: ${reboot_timeout}

ota:
  - platform: esphome
    password: !secret ota_password

time:
  - platform: homeassistant
    id: homeassistant_time

ethernet:
  type: W5500
  mosi_pin: GPIO06
  miso_pin: GPIO04
  clk_pin: GPIO7
  cs_pin: GPIO10
  reset_pin: GPIO05
  interrupt_pin: GPIO03
  clock_speed: 40MHz
  manual_ip:
    static_ip: ${static_ip}
    gateway: '192.168.20.1'
    subnet: '255.255.255.0'
    dns1: '192.168.1.70'
    dns2: '192.168.1.80'

uart:
  - id: hp_uart
    baud_rate: 2400
    parity: EVEN
    rx_pin: { number: GPIO1 }
    tx_pin: { number: GPIO0 }
  - id: tstat_uart
    baud_rate: 2400
    parity: EVEN
    rx_pin: { number: GPIO20 }
    tx_pin: { number: GPIO21 }

climate:
  - platform: mitsubishi_itp
    name: "Climate"
    uart_heatpump: hp_uart
    uart_thermostat: tstat_uart
    update_interval: 6s

binary_sensor:
  - platform: mitsubishi_itp
    defrost: { name: "Defrost" }
    filter_status: { name: "Filter Status" }
    isee_status: { name: "i-see Status" }
    preheat: { name: "Preheat" }
    standby: { name: "Standby" }
    using_internal_temperature: { name: "Internal Sensor" }

sensor:
  - platform: mitsubishi_itp
    compressor_frequency: { name: "Compressor Frequency" }
    outdoor_temperature: { name: "Outdoor Temperature" }
    thermostat_temperature: { name: "Thermostat Temperature" }
  - platform: uptime
    name: "Uptime"
  - platform: internal_temperature
    name: "Internal Temperature"
    accuracy_decimals: 2
    update_interval: 30s

text_sensor:
  - platform: mitsubishi_itp
    actual_fan: { name: "Actual Fan" }
    error_code: { name: "Error Code" }

button:
  - platform: mitsubishi_itp
    filter_reset_button: { name: "Filter Reset" }
  - platform: restart
    name: "Restart"

select:
  - platform: mitsubishi_itp
    vane_position: { name: "Vane Position" }
    horizontal_vane_position: { name: "H. Vane Position" }
    temperature_source:
      name: "Temperature Source"
      sources: []

light:
  - platform: status_led
    name: "Status LED"
    pin:
      number: GPIO08
      inverted: true
      ignore_strapping_warning: true
    internal: true
